# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 01cde6c61c349bc6e56553b7f0c4fb7013f7a7a5c7a395e5e3222bd0338a3ec5be9fdf66bad078618ed32d4cd4bf2d04574b4b211fe71e4177f78e10ad73449e

test:
  secret_key_base: 1d73feca76aa7043bb40498961635d4d9da40861047c55b1fcbd05d4e3a8c15a270994ed21dd349d3faf640c362fba917346260e65af110a063057e9c9e4681a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
